### ISSUE TITLE
Extremely slow connection creation time - unusable for serverless

### ISSUE THREAD

**Issue by danaugrs** [planetscale/planetscale-node#20]
I've been evaluating PlanetScale for use with serverless applications (specifically [NextJS](https://nextjs.org)). I love the CLI and database offering, but I've found that `planetscale-node` at its current state is unusable for serverless applications.

In the serverless paradigm, each request to a cloud function will create a new connection to the database. With `planetscale-node`, creating a connection and executing the first query consistently takes more than three seconds, sometimes even four (!). (Subsequent queries take ~150ms).

I did some digging and found that the great majority (~96%) of that time is spent waiting for a POST request to create a TLS certificate, prior to starting the database connection itself (see [`postJSON`](https://github.com/planetscale/planetscale-node/blob/main/src/index.ts#L49)).

Is it expected for certificate creation to take that long?
Are there any plans to support serverless applications?

**Comment by mscoutermarsh** [comment]
@danaugrs Thanks for opening this. Yes, we're working on this now and will make an update to the node library when it's ready.

**Comment by mscoutermarsh** [comment]
Here's some more discussion: https://github.com/planetscale/beta/discussions/15. I hope to have more to share soon! 😄

**Comment by danaugrs** [comment]
Wonderful, thanks!

**Comment by JuniorDEVed** [comment]
Any updates on when this might be sorted? I am currently running fullstack serverless application on aws, interested to use PlanetScale instead of dynamodb for our use case, but keep reading that currently planetscale is unusable on lambda?

**Comment by mscoutermarsh** [comment]
We're on it! We're testing it internally now, available to everyone soon.

**Comment by mscoutermarsh** [comment]
We just shipped https://planetscale.com/blog/connect-any-mysql-client-to-planetscale-using-connection-strings.

You can now generate a password + connection string in the UI and connect directly without using this library. We've tested it on both lambda + vercel and it fixed the performance issue caused by the cert issue.
