### ISSUE TITLE
Using native ORM client to perform request to PlanetScale without using the CLI at first place

### ISSUE THREAD

**Issue by dbrrt** [planetscale/planetscale-node#25]
I can't find a clear way to run my queries on PlanetScale other than going through this library or should I use this library as a connection intermediary to power my existing ORM nodeJS (sequelize) without having to do the initial handshake with the CLI `pscale connect <my-db> main --execute '<my-app-main>'`?

Is there a reference for the correct way to do this?

**Comment by mscoutermarsh** [comment]
We're working on it! Will share an update soon.

**Comment by dbrrt** [comment]
Thanks for the update!

**Comment by mscoutermarsh** [comment]
Hi @dbrrt, we just shipped: https://planetscale.com/blog/connect-any-mysql-client-to-planetscale-using-connection-strings

Now you can generate a connection string and connect directly without using this library or `pscale connect`.
