### ISSUE TITLE
does this work with AWS lambda yet?

### ISSUE THREAD

**Issue by JuniorDEVed** [planetscale/planetscale-node#26]
Hi,

Can't wait to get stuck into this, does this work with aws lambda yet?

Bests,

Sean.

**Comment by tbarn** [comment]
Hey @JuniorDEVed! We've got some stuff coming out in the next couple of weeks that will make working with AWS Lambda a lot better. Stay tuned!

**Comment by mscoutermarsh** [comment]
Hi @JuniorDEVed,

We just shipped this: https://planetscale.com/blog/connect-any-mysql-client-to-planetscale-using-connection-strings

For Lambda we recommend creating a password and then using a direct connection string (rather than this library).
